#!/usr/bin/env php
<?php

use Source\Kernel;
use Source\Spaces;

if (is_file(dirname(__DIR__).'/vendor/autoload.php')) {
    require_once dirname(__DIR__).'/vendor/autoload.php';
}

new Kernel(__DIR__)->run(Spaces::Tests);
